REM INSERTING into SYSTEM.MATCH
SET DEFINE OFF;
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Alberti','Pako Casal','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Fronk','OSUM','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Pedro','Galazeth','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Menta','Kadena','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Menta','Vaya y Coja Leveler','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Hernan','Nalia','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Matemole','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Alberti','Vadrok','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Matemole','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Brian','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Pato','Pit y Dark Pit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Pedro','Galazeth','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Pato','Samurai Waifus','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Pedro','Galazeth','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Saico','Tivit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Mari','OSUM','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Pato','Pit y Dark Pit','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Saico','Tivit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Bug','Yidris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Menta','Vaya y Coja Leveler','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Pato','Samurai Waifus','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Bug','Cascada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Alberti','Pako Casal','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Alberti','La Peruana','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Matemole','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Brian','Karrthus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Cremongo','Shrines','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Cremongo','Shrines','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Pato','Samurai Waifus','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Matemole','La Peruana','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Menta','El Oso Hijo de Puta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Fanca','Nalia','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Alberti','Pako Casal','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Hernan','Shackled Sefris','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Pato','Samurai Waifus','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Brian','Atarka ataka','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Pulga','Codie','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Pato','Pit y Dark Pit','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Saico','Araumi','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Rigo','La Peruana','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Hernan','Shackled Sefris','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Pato','Samurai Waifus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Menta','El Oso Hijo de Puta','N');
