--------------------------------------------------------
--  File created - Monday-April-17-2023   
--------------------------------------------------------
REM INSERTING into SYSTEM.MATCH
SET DEFINE OFF;
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),1,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Pato','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),3,'Brian','Atarka ataka','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Pulga','Codie','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),4,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),5,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),6,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Pato','Pit y Dark Pit','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),7,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),8,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),9,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),10,'Saico','Araumi','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Rigo','La Peruana','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),11,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Hernan','Shackled Sefris','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('27-JAN-23','DD-MON-RR'),12,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),1,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Menta','El Oso Hijo de Puta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Fanca','Nalia','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Alberti','Pako Casal','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),3,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Hernan','Shackled Sefris','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('28-JAN-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),2,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Brian','Karrthus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Cremongo','Shrines','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),4,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),5,'Cremongo','Shrines','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Pato','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),1,'Matemole','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Matemole','La Peruana','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-FEB-23','DD-MON-RR'),7,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('06-FEB-23','DD-MON-RR'),1,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),1,'Bug','Eterno Tormento','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Pato','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Menta','Vaya y Coja Leveler','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),2,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Bug','Eterno Tormento','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Alberti','Pako Casal','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),4,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-FEB-23','DD-MON-RR'),5,'Alberti','La Peruana','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Pato','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),1,'Pedro','Galazeth','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Saico','Tivit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),2,'Mari','OSUM','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Pato','Pit y Dark Pit','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-FEB-23','DD-MON-RR'),3,'Saico','Tivit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),1,'Matemole','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Alberti','Vadrok','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Matemole','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Pato','Pit y Dark Pit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Brian','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('18-FEB-23','DD-MON-RR'),3,'Pedro','Galazeth','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Alberti','Pako Casal','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),1,'Fronk','OSUM','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),3,'Pedro','Galazeth','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Menta','Kadena','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),4,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Menta','Vaya y Coja Leveler','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Hernan','Nalia','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('19-FEB-23','DD-MON-RR'),5,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),1,'Alberti','Vadrok','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),1,'Saico','Araumi','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),1,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),1,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),2,'Pedro','La Mansion de Volo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),2,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),3,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),3,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),3,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),4,'Pedro','La Mansion de Volo','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),4,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),4,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),4,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),5,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),5,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),5,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('21-FEB-23','DD-MON-RR'),5,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),1,'Pedro','La Mansion de Volo','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),1,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),1,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),1,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),2,'Saico','Tivit','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),2,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('22-FEB-23','DD-MON-RR'),2,'Alberti','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),1,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),1,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),1,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),1,'Menta','OSUM','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),2,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),2,'Menta','Kadena','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),2,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),3,'Menta','Vaya y Coja Leveler','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),3,'Alberti','Vota bien','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),3,'Rigo','Karrthus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('24-FEB-23','DD-MON-RR'),3,'Mitsu','OSUM','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),1,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),1,'Fronk','OSUM','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),1,'Mitsu','Ukkima','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),2,'Mitsu','Ukkima','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),2,'Menta','Kadena','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),2,'Alberti','Vota bien','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),2,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),3,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),3,'Pedro','La Mansion de Volo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-FEB-23','DD-MON-RR'),3,'Pulga','La Osa Ruxa','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),1,'Bug','Eterno Tormento','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),1,'Pedro','La Mansion de Volo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),1,'Mitsu','Ukkima','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),2,'Bug','Eterno Tormento','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),2,'Pedro','La Mansion de Volo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),2,'Mitsu','Ukkima','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),2,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),3,'Pato','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),3,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),3,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),3,'Enema','Mamut mega','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),4,'Pedro','La Mansion de Volo','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),4,'Menta','Avacyn','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),4,'Mitsu','Ukkima','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),4,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),5,'Pedro','La Mansion de Volo','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),5,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),5,'Mitsu','Ukkima','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),6,'Enema','Mamut mega','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),6,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),6,'Brian','Tom Hardy','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('02-MAR-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-MAR-23','DD-MON-RR'),1,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-MAR-23','DD-MON-RR'),1,'Enema','Mamut mega','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-MAR-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-MAR-23','DD-MON-RR'),1,'Saico','Vaya y Coja Leveler','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),1,'Pedro','Galazeth','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),1,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),1,'Menta','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),2,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),2,'Alberti','Vota bien','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),2,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),2,'Z','Etali','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),3,'Brian','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),3,'Alberti','Vota bien','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),3,'Menta','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),4,'Menta','Marchesa','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),4,'Mitsu','Avacyn','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),4,'Brian','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),4,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),5,'Brian','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),5,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),5,'Menta','Marchesa','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),5,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),6,'Pato','Cynonari','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),6,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),6,'Alberti','Vota bien','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-MAR-23','DD-MON-RR'),6,'Brian','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('16-MAR-23','DD-MON-RR'),1,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('16-MAR-23','DD-MON-RR'),1,'Brian','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('16-MAR-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('16-MAR-23','DD-MON-RR'),1,'Pedro','Te tengo Ganax','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),1,'Pedro','Te tengo Ganax','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),1,'Pato','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),1,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),1,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),2,'Pedro','Te tengo Ganax','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),2,'Hernan','Nalia','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),2,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),2,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),3,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),3,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),3,'Hernan','Shackled Sefris','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('23-MAR-23','DD-MON-RR'),3,'Pedro','Te tengo Ganax','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),1,'Pato','Cynonari','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),1,'Pedro','Mazo Saicola','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),1,'Menta','Marchesa','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),1,'Freak','El Oso Hijo de Puta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),2,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),2,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),2,'Enema','Mamut mega','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),2,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),3,'Brian','Bayonetta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),3,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),3,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('26-MAR-23','DD-MON-RR'),3,'Matemole','Sythis','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),1,'Pato','Cynonari','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),1,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),1,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),2,'Saico','Araumi','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),2,'Alberti','La Peruana','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),2,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),2,'Matemole','Sythis','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),3,'Matemole','Sythis','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),3,'Alberti','Vadrok','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),3,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),3,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),4,'Brian','Bayonetta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),4,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),4,'Matemole','Sythis','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),4,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),5,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),5,'Matemole','Sythis','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),5,'Pato','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('30-MAR-23','DD-MON-RR'),5,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),1,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),1,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),1,'Alberti','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),2,'Menta','Marchesa','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),2,'Marroll','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),2,'Pato','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),2,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),3,'Alberti','Kadena','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),3,'Pedro','Mazo Saicola','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),3,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),3,'Mitsu','Ukkima','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),4,'Menta','Marchesa','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),4,'Mitsu','Avacyn','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),4,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),4,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),5,'Menta','Marchesa','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),5,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),5,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),5,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),6,'Brian','Bayonetta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),6,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),6,'Menta','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),6,'Pato','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),7,'Enema','Mamut mega','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),7,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),7,'Marroll','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),7,'Rigo','Karrthus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),8,'Enema','Mamut mega','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),8,'Mitsu','Ukkima','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),8,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),8,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),9,'Salieri','Incineroar','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),9,'Matemole','Sythis','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),9,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('01-APR-23','DD-MON-RR'),9,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),1,'Rigo','La Triple G','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),1,'Pedro','Mazo Saicola','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),1,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),1,'Alberti','La Teletón','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),2,'Pedro','Mazo Saicola','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),2,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),2,'Enema','Muldrotha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('04-APR-23','DD-MON-RR'),2,'Mitsu','Avacyn','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-APR-23','DD-MON-RR'),1,'Salieri','Te tengo Ganax','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-APR-23','DD-MON-RR'),1,'Freak','Leandro Paredes','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-APR-23','DD-MON-RR'),1,'Menta','Marchesa','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('05-APR-23','DD-MON-RR'),1,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),1,'Pedro','Mazo Saicola','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),1,'S','Dihada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),1,'Robo','Strefan, el de los tokens','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),1,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),2,'Vikinga','La Osa Ruxa','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),2,'Pulga','Aminatou','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),2,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),2,'Kiki','Karrthus','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),3,'Bug','Grixis Mishra','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),3,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),3,'S','Blim','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('07-APR-23','DD-MON-RR'),3,'Pato','Kaedehara Kazuha','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),1,'Menta','Kadena','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),1,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),1,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),1,'Alberti','La Teletón','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),2,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),2,'Pato','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),1,'Lazerth','Leandro Paredes','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),1,'Alberti','La Teletón','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),2,'Mitsu','Rak dos','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('08-APR-23','DD-MON-RR'),2,'Alberti','Leandro Paredes','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),1,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),1,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),2,'Brian','Bayonetta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),2,'Mitsu','La Peruana','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),2,'Alberti','Vota bien','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),2,'Lazerth','Vashla Estampida','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),3,'Pato','Cynonari','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),3,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),3,'Mitsu','La Peruana','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),3,'Alberti','Leandro Paredes','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),4,'Pato','Kaedehara Kazuha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),4,'Mitsu','La Peruana','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),4,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('09-APR-23','DD-MON-RR'),4,'Alberti','La Teletón','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),1,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),1,'Alberti','Leandro Paredes','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),1,'Pato','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),1,'Bug','Eterno Tormento','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),2,'Bug','Urza Army','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),2,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),2,'Pato','Cynonari','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),2,'Saico','Tivit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),3,'Brian','Bayonetta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),3,'Bug','Eterno Tormento','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),3,'Alberti','La Teletón','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),3,'Saico','Saiconnives','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),4,'Enema','Muldrotha','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),4,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),4,'Pedro','Mazo Saicola','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),4,'Brian','Bayonetta','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),5,'Brian','Bayonetta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),5,'Rigo','La Triple G','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),5,'Mitsu','Rak dos','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),5,'Pedro','Mazo Saicola','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),6,'Saico','Saiconnives','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),6,'Enema','Mamut mega','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),6,'Denis','La Gilada de Giada','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),6,'Pedro','Mazo Saicola','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),7,'Denis','La Gilada de Giada','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),7,'Pato','Pit y Dark Pit','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),7,'Saico','Incineroar','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('15-APR-23','DD-MON-RR'),7,'Mitsu','Yasuo','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-APR-23','DD-MON-RR'),1,'Brian','Bayonetta','Y');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-APR-23','DD-MON-RR'),1,'Alberti','Pako Casal','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-APR-23','DD-MON-RR'),1,'Mitsu','La Peruana','N');
Insert into SYSTEM.MATCH (MATCH_DATE,MATCH_NUMBER,PLAYER,DECK,WINNER_CHECK) values (to_date('17-APR-23','DD-MON-RR'),1,'Denis','La Gilada de Giada','N');
